### ISSUE TITLE
LM358

### ISSUE THREAD

**Issue by YKolokoltsev** [rene-dev/stmbl#103]
Hello. This is more like a hint, not an issue so I write it in an open form.

Your file  stmbl/hw/spice/LM358.lib was quite helpful for my Eagle simulations, however it contains a model of just one OpAmp and LM358 is a dual op amp IC. You can change it by adding the following lines in the beginning:

```
.SUBCKT LM358_DUAL       IN1+ IN1- OUT1 IN2+ IN2- OUT2 V+ V-
X_OPAMP1 IN1+ IN1- V+ V- OUT1 LM358
X_OPAMP2 IN2+ IN2- V+ V- OUT2 LM358
.ENDS
```
And use than `LM358_DUAL` in your Eagle. I do not know if you are really using a dual OpAmp, but I believe that this information can be useful anyway.

**Comment by crinq** [comment]
Thanks for the info.
We use this lib only for the ltspice simulation of the feedback interface (wich uses only a single opamp).
