### ISSUE TITLE
STMBL not reseting encoder in encws_fbx

### ISSUE THREAD

**Issue by MarkusBec** [rene-dev/stmbl#104]
## Here are the steps I follow to reproduce the issue:

 1. hab ich so gemacht
 2. stmbl hat so gemacht
 3. kaputt

## This is what I expected to happen:

correkt detection of UVW position 

## This is what happened instead:

nor working with soft reset 

## It worked properly before this:
(If the behavior changed after making a particular change in hardware or
software, describe the change you think is responsible.)

## Information about my hardware and software:

 * Complete config (known)
 * Firmware version (known)
 * I am using this Hardware version, from this source

**Comment by Sync-** [comment]
![image](https://user-images.githubusercontent.com/3520058/77013193-d8ee3e80-696f-11ea-825c-e98617c0957d.png)
