### ISSUE TITLE
Price of the part for building it ?

### ISSUE THREAD

**Issue by nathmo** [rene-dev/stmbl#117]
Hi, 
i'm trying to compare different open-source brushless controller and yours is really impressive but i can't find an estimation of the price in what i read. would it be possible to mention it in the README ?

many thanks !

## Here are the steps I follow to reproduce the issue:
Open the README

## This is what I expected to happen:
find the information in the README

## This is what happened instead:
can't find the information easily.

## It worked properly before this:
NA
## Information about my hardware and software:
NA

**Comment by crinq** [comment]
It's impossible to mention a reproducable price right now, as some components are not available and prices of others vary greatly with quantity and time.
About 3 years ago the cheapest was about 65€ (only parts) + assembly + work + ...
Right now if you could get all the parts maybe 100-250€
