### ISSUE TITLE
the PCB' avaiable now?

### ISSUE THREAD

**Issue by hqkhuong** [rene-dev/stmbl#19]
hi, i want to build one cnc machine for router woodworking, last time i using stepper to driven, so sometime lost step, this is not good, and also i check the price at ebay, but very expensive, therefore, i want to build that one. Could you pls help me to provide PCB's , driver BOB, plan etc..
Tell me by my email hqkhuong@gmail.com about price and your supported when i start my project, Thanks so much for your undstanding with my English

**Comment by rene-dev** [comment]
I just send you an email.

**Comment by hqkhuong** [comment]
thanks so much, i will check

2015-11-18 20:47 GMT+07:00 Rene Hopf <notifications@github.com>:

> I just send you an email.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rene-dev/stmbl/issues/19#issuecomment-157717989>.
>



-- 

*Hoàng Quốc KhươngMobile: (+84).982.117.409*
