### ISSUE TITLE
Does not build with most recent gcc-arm-none-eabi 4.9.3 x64

### ISSUE THREAD

**Issue by aShure** [rene-dev/stmbl#21]
Tested with ubuntu wily x64, a standard apt-get gcc-arm-none-eabi yields version 4.9.3.

```
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: error: hv_firmware.o: Conflicting CPU architectures 13/0
/usr/lib/gcc/arm-none-eabi/4.9.3/../../../arm-none-eabi/bin/ld: failed to merge target specific data of file hv_firmware.o
collect2: error: ld returned 1 exit status
Makefile:72: recipe for target 'main.elf' failed
make: *** [main.elf] Error 1
```

FYI: Makefile from https://github.com/synthetos/g2 downloads an older gcc-arm-none-eabi in 32bit, hard linking to it for compilation, then libz32 is needed on x64 systems.

**Comment by rene-dev** [comment]
use this compiler, https://launchpad.net/gcc-arm-embedded/+download
the one that ships with distros is known to cause various problems.
https://answers.launchpad.net/gcc-arm-embedded/+question/253999
