### ISSUE TITLE
implement hardfault handler

### ISSUE THREAD

**Issue by rene-dev** [rene-dev/stmbl#50]
https://github.com/rene-dev/stmbl/blob/master/src/stm32f4xx_it.c#L55
example: https://github.com/thomask77/drquad32/blob/master/Source/fault_handler.c#L19
- [x] NAN trap in HAL
- [x] hardfault handler
- [x] watchdog #48

**Comment by crinq** [comment]
- [ ] NAN trap in HAL
- [ ] hardfault handler
- [ ] watchdog
