### ISSUE TITLE
Can't open Kicad files with current version of KiCad

### ISSUE THREAD

**Issue by saeugetier** [rene-dev/stmbl#62]
I tried to open the pcbnew file of the STMBL V4.0 with KiCad Version 4.0.2 and 4.0.6 (latest version). The file could not be parsed. The error is:

```
PARSE_ERROR: Expecting 'clearance, trace_width, via_dia, via_drill, uvia_dia, uvia_drill, or add_net' in input/source
'..../source/stmbl/hw/kicad/v4.0/stmbl_4.0.kicad_pcb'
line 336
offset 6
from /build/kicad-BIvGIy/kicad-4.0.2+dfsg1/common/dsnlexer.cpp : Expecting() : line 369
```
It seems that there are unexpected properties in the file.

```
  (diff_pair_gap 0.25)
    (diff_pair_width 0.2)
```

Which version are you using?

**Comment by crinq** [comment]
Hi,
use the nightly build: http://downloads.kicad-pcb.org/<OS>/nightly/
