### ISSUE TITLE
Source:I did not find the source

### ISSUE THREAD

**Issue by chxb1987** [rene-dev/stmbl#67]
hello, I did not find the software source in your project. can you give me a favour

**Comment by crinq** [comment]
F4 bootloader: [bootloader](https://github.com/rene-dev/stmbl/tree/master/bootloader)
F4 firmware: [src](https://github.com/rene-dev/stmbl/tree/master/src) + [inc](https://github.com/rene-dev/stmbl/tree/master/inc)
F3 bootloader: [f3dfu](https://github.com/rene-dev/stmbl/tree/master/f3dfu)
F3 firmware: [stm32f303](https://github.com/rene-dev/stmbl/tree/master/stm32f303)
Shared stuff: [shared](https://github.com/rene-dev/stmbl/tree/master/shared)
Runtime configuration: [conf](https://github.com/rene-dev/stmbl/tree/master/conf)
Configuration tool: https://github.com/STMBL/Servoterm-app
HAL configuration plotter: [graphviz](https://github.com/rene-dev/stmbl/tree/master/graphviz)
CPU libs: [lib](https://github.com/rene-dev/stmbl/tree/master/lib)
Hardware files: [hw](https://github.com/rene-dev/stmbl/tree/master/hw)

*/comps folders contain C modules, that can be instantiated at runtime.
