### ISSUE TITLE
stmbl with Keil µvision v5 IDE

### ISSUE THREAD

**Issue by feiyg** [rene-dev/stmbl#70]
hi,
 I am trying to compile the whole project using Keil µvision v5 but I have a little errors that I am not able to resolve.

compiling main.c...
..\src\comps/adc.comp(29): error:  #65: expected a ";"
  RT(
..\src\main.c: 0 warnings, 1 error

**Comment by crinq** [comment]
- We don't support Keil.
- That is old code. Use the current master branch.
