### ISSUE TITLE
File issues

### ISSUE THREAD

**Issue by Sastas** [rene-dev/stmbl#73]
I'm pretty new to github, and even to this project.
I'm not really understand where I can have the current(V4.1?) board files, to be able to make them.
I click trough every single folder in the project I think, but found only 3.4 or older, and some kicad files with 4.0 tags, but kicad unable to open them in my pc.
I'm really confused about it. Or the project lost its contributors?

**Comment by crinq** [comment]
current board files: https://github.com/rene-dev/stmbl/tree/master/hw/kicad/v4.0
you need kicad nightly: http://downloads.kicad-pcb.org/_YOUR_OS_/nightly/
see: #62
