### ISSUE TITLE
stmbl with Keil µvision v5 IDE 

### ISSUE THREAD

**Issue by sacidu93** [rene-dev/stmbl#9]
hi,
I am trying to compile the whole project using Keil µvision v5 but I have a little errors that I am not able to resolve, the compiler reports 28 error messages like this:

"src\comps/brake.comp(18): error:  #29: expected an expression" .

when clicking on the message, the line containing "INIT(" , "NRT(" and "RT(" lines are highlighted in all .comp files.

The f103 project compile with no error ( after activating --C99 option for compiler and adding USE_STDPERIPH_DRIVER macro ).

Any one have an idea how to resolve this ?
thanks.

**Comment by crinq** [comment]
Hi,
try gcc. 
Our HAL implementation (src/hal.h and .c) uses some preprocessor magic only tested on gcc. 
It "should" work with other compilers, but we have no time to build and test against others. 
If you find a simple fix we will look at it.
A good starting point for debugging is the preprocessed source code (option -E).
