### ISSUE TITLE
STMBL is

### ISSUE THREAD

**Issue by feiyg** [rene-dev/stmbl#92]
Does stmbl support sensorless control?

**Comment by rene-dev** [comment]
currently not, but the hardware has all capabilities to do so.
stmbl is designed for servos, and servos have by definition always feedback.

**Comment by feiyg** [comment]
okey,thanks.
but another one (ottercontrol) also needs feedback?

**Comment by rene-dev** [comment]
yes, its based on an older version of stmbl code.

**Comment by feiyg** [comment]
i get it,thank you!
