### ISSUE TITLE
documentation of torque constant - different units used.

### ISSUE THREAD

**Issue by c-morley** [rene-dev/stmbl#95]
On this page:
https://github.com/rene-dev/stmbl/wiki/motor-parameters
mentions torque constant (conf0.psi) in v*s/rad units

This page:
https://github.com/rene-dev/stmbl/blob/master/docs/src/Getting%20Started.adoc
under motor parameters mentions torque constant (conf0.psi) in Nm/a units

1) I believe conf0.psi units is Ke with units of volts/rad/second which seems to be voltage constant.
This can be rms voltage or peak? voltage - does the stmbl use peak voltage?

2) The description to use stml to do a PSI test doesn't seem to work - after pasting code servoterm complains = no psi0.max_psi

**Comment by crinq** [comment]
v*s/rad is equal to Nm/A
Doc and psi config should be fixed now.
The concepts of RMS and peak do not apply in this case.
