### ISSUE TITLE
WHERE BUY A FULL STMBL 

### ISSUE THREAD

**Issue by TECAUTOMACAO** [rene-dev/stmbl#96]
HELLOW FRENDS , IM FROM BRAZIL , AND I WANT BUY A FULL STMBL , WHERE I CAN BUY AND SEND MI TO BRAZIL ?

**Comment by crinq** [comment]
We are currently out of stock.

**Comment by crinq** [comment]
The IGBT module in v4 is EOL and out of stock. You should wait for the next STMBL version.

**Comment by TECAUTOMACAO** [comment]
HI Nico , yes i want wait , when you can send me ? how much $  ? can you
send me ready ? 

Em 2018-10-19 00:37, Nico Stute escreveu:

> The IGBT module in v4 is EOL and out of stock. You should wait for the next STMBL version. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 

Renato Cassa 
Departamento Técnico
RA Cassa Automação Epp Ltda.
015-99715-3290

 

Links:
------
[1] https://github.com/rene-dev/stmbl/issues/96#issuecomment-431234896
[2]

**Comment by TECAUTOMACAO** [comment]
Em 2018-10-20 13:46, Renato Cassa TEC AUTOMAÇAO escreveu:

> HI Nico , yes i want wait , when you can send me ? how much $  ? can you send me ready ? 
> 
> Em 2018-10-19 00:37, Nico Stute escreveu:
> 
>> The IGBT module in v4 is EOL and out of stock. You should wait for the next STMBL version. 
>> 
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
> 
> -- 
> 
> Renato Cassa 
> Departamento Técnico
> RA Cassa Automação Epp Ltda.
> 015-99715-3290

HI Nico , yes i want wait , when you can send me ? how much $  ? can you
send me ready ? 

Em 2018-10-19 00:37, Nico Stute escreveu:

> The IGBT module in v4 is EOL and out of stock. You should wait for the next STMBL version. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 

Renato Cassa 
Departamento Técnico
RA Cassa Automação Epp Ltda.
015-99715-3290 

Renato Cassa 
Departamento Técnico
RA Cassa Automação Epp Ltda.
015-99715-3290

 

Links:
------
[1] https://github.com/rene-dev/stmbl/issues/96#issuecomment-431234896
[2]

**Comment by TECAUTOMACAO** [comment]
Em 2018-10-19 00:37, Nico Stute escreveu:

> The IGBT module in v4 is EOL and out of stock. You should wait for the next STMBL version. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

Helow frends , i want buy stmbl , is  available

-- 

Renato Cassa 
Departamento Técnico
RA Cassa Automação Epp Ltda.
015-99715-3290

 

Links:
------
[1] https://github.com/rene-dev/stmbl/issues/96#issuecomment-431234896
[2]

**Comment by crinq** [comment]
no
